stages:
  - build
  - deploy

variables:
  # This builds the full path to your Google Artifact Registry
  IMAGE: $REGION-docker.pkg.dev/$GCP_PROJECT_ID/my-app-repo/my-app
  DOCKER_TLS_CERTDIR: "" 

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    # Login using the File variable
    - cat $GCP_SERVICE_KEY | docker login -u _json_key --password-stdin https://$REGION-docker.pkg.dev
    # Build and Push
    - docker build -t $IMAGE:$CI_COMMIT_SHA .
    - docker push $IMAGE:$CI_COMMIT_SHA

deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    # 1. Authenticate
    - gcloud auth activate-service-account --key-file=$GCP_SERVICE_KEY
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud container clusters get-credentials $GKE_CLUSTER_NAME --region $REGION

    # 2. Replace placeholders in deployment.yaml
    - sed -i "s|REGION|$REGION|g" k8s/deployment.yaml
    - sed -i "s|PROJECT_ID|$GCP_PROJECT_ID|g" k8s/deployment.yaml
    - sed -i "s|IMAGE_TAG|$CI_COMMIT_SHA|g" k8s/deployment.yaml

    # 3. Apply to Kubernetes
    # First, create the namespace
    - kubectl apply -f k8s/namespace.yaml
    # Deploy the app and service into that namespace
    - kubectl apply -n project-dev -f k8s/deployment.yaml
    - kubectl apply -n project-dev -f k8s/service.yaml