stages:
  - build
  - deploy_gke      # For Backend
  - deploy_cloudrun # For Frontend

variables:
  # Two different image paths
  FRONT_IMAGE: $REGION-docker.pkg.dev/$GCP_PROJECT_ID/my-app-repo/frontend
  BACK_IMAGE: $REGION-docker.pkg.dev/$GCP_PROJECT_ID/my-app-repo/backend
  DOCKER_TLS_CERTDIR: "" 

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cat $GCP_SERVICE_KEY | docker login -u _json_key --password-stdin https://$REGION-docker.pkg.dev
    # Build and Push Backend
    - docker build -t $BACK_IMAGE:$CI_COMMIT_SHA -f Dockerfile.backend .
    - docker push $BACK_IMAGE:$CI_COMMIT_SHA
    # Build and Push Frontend
    - docker build -t $FRONT_IMAGE:$CI_COMMIT_SHA -f Dockerfile.frontend .
    - docker push $FRONT_IMAGE:$CI_COMMIT_SHA

deploy_backend_to_gke:
  stage: deploy_gke
  image: google/cloud-sdk:latest
  script:
    - gcloud auth activate-service-account --key-file=$GCP_SERVICE_KEY
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud container clusters get-credentials $GKE_CLUSTER_NAME --region $REGION
    # Update the GKE manifest for the backend
    - sed -i "s|REGION|$REGION|g" k8s/backend.yaml
    - sed -i "s|PROJECT_ID|$GCP_PROJECT_ID|g" k8s/backend.yaml
    - sed -i "s|IMAGE_TAG|$CI_COMMIT_SHA|g" k8s/backend.yaml
    # Apply
    - kubectl apply -f k8s/namespace.yaml
    - kubectl apply -f k8s/backend.yaml

deploy_frontend_to_cloudrun:
  stage: deploy_cloudrun
  image: google/cloud-sdk:latest
  script:
    - gcloud auth activate-service-account --key-file=$GCP_SERVICE_KEY
    - gcloud config set project $GCP_PROJECT_ID
    # Deploy to Cloud Run and inject the Backend IP via environment variable
    - gcloud run deploy frontend-service 
      --image $FRONT_IMAGE:$CI_COMMIT_SHA 
      --platform managed 
      --region $REGION 
      --allow-unauthenticated
      --set-env-vars BACKEND_URL=$BACKEND_URL