apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend
  namespace: project-dev
spec:
  replicas: 1
  strategy:
    type: Recreate # This stops the old pod before starting the new one to save resources
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/harsha-01-497805/demo/backend:v1
        ports:
        - containerPort: 5000
        # GKE Autopilot works best with these specific resource requests
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
  namespace: project-dev
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 5000