apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: REGION-docker.pkg.dev/PROJECT_ID/my-app-repo/my-app:IMAGE_TAG
        ports:
        - containerPort: 3000