name: First GitHub Action

on:
  push:

jobs:
  explore-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "GitHub Actions Started"

      - name: Show Current Directory
        run: pwd

      - name: List Files
        run: ls -la