name: Node.js CI Pipeline

on:
  push:

jobs:
  nodejs-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Verify Node.js
        run: node -v

      - name: Verify npm
        run: npm -v

      - name: Install Dependencies
        run: npm install

      - name: Run Application
        run: node app.js