name: Full CI/CD Pipeline

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Configure Docker Authentication
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: |
          docker build \
          -f Dockerfile.frontend \
          -t asia-south1-docker.pkg.dev/harsha-497107/demo/frontend:v1 .

      - name: Push Docker Image
        run: |
          docker push \
          asia-south1-docker.pkg.dev/harsha-497107/demo/frontend:v1

      - name: Connect to GKE Cluster
        run: |
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True

          gcloud container clusters get-credentials demo-cluster \
          --region asia-south1 \
          --project harsha-497107

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Verify Deployment
        run: |
          kubectl get pods -n project-dev
          kubectl get services -n project-dev